FROM golang:1.19.1 AS builder

WORKDIR /app
COPY . .

RUN go build -o /app/webapi ./cmd/webapi

FROM debian:bullseye

WORKDIR /app
COPY --from=builder /app/webapi .
COPY --from=builder /app/service /app/service

RUN mkdir -p /app/webui/public && chmod -R 777 /app/webui

RUN mkdir -p /app/service/db && chmod 777 /app/service/db

EXPOSE 3000
CMD ["./webapi"]
